/**
 * generated by Xtext
 */
package istic.idm.project.ui.contentassist;

import istic.idm.project.ui.contentassist.AbstractVideoGenProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class VideoGenProposalProvider extends AbstractVideoGenProposalProvider {
}
