/**
 * generated by Xtext
 */
package istic.idm.project.validation;

import istic.idm.project.validation.AbstractVideoGenValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VideoGenValidator extends AbstractVideoGenValidator {
}
