/*
 * generated by Xtext
 */
package istic.idm.project.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractVideoGenValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(istic.idm.project.videoGen.VideoGenPackage.eINSTANCE);
		return result;
	}
}
